module.exports = {
  plugins: [`gatsby-plugin-sass`],
  siteMetadata: {
    title: `Jingfu's portfolio`,
    description: `Hello! My name is Jingfu Dong, welcome to my portfolio site. I'm looking for job, you can download my resume.`,
    author: `Jingfu Dong`,
    projects: [
      {
        id: 1,
        title: `Ad word configurator`,
        github_url: `https://github.com/Dongongngg/ad-words-test`,
        description: `Code challenge I did for a marketing company. Full-stack app that allow users to store keywords/sites and settings which pre-populated from previous opertaion.`,
        img: `img/projects/code-test/ad-word.png`,
        skills: `React | Material UI | Express | Sequelize | NodeJS | MySQL | Docker | REST api`,
      },
      {
        id: 2,
        title: `Job-listing(MERN)`,
        github_url: `https://github.com/Dongongngg/job-listing`,
        description: `Full-stack application that allows users to register/login, then create, update, delete, filter their job applications.`,
        img: `img/projects/job-listing/job-listing.png`,
        skills: `NodeJS | Express | React | Mongoose | MongoDB | JWT | REST api`,
      },
      {
        id: 3,
        title: `My Portfolio`,
        github_url: `https://github.com/Dongongngg/portfolio`,
        netlify_url: `https://jingfudong.com`,
        description: `Graphql, Gatsby and Netlify deployment. Trying to make it clear.`,
        img: `img/projects/portfolio/landing.png`,
        skills: `Gatsby | React | Bootstrap | SASS | Graphql`,
      },
      // {
      //   id: `4`,
      //   title: `COVID-19 stats`,
      //   github_url: `https://github.com/Dongongngg/covid19-au-stats`,
      //   netlify_url: `https://covid-19-au.netlify.app/`,
      //   description: `Fetch and display daily COVID19 stats from API`,
      //   img: `img/projects/covid19-au-stats/overall.png`,
      //   skills: `React | Material UI | SASS`,
      // },
    ],
    works: [
      {
        id: 1,
        title: `Full-stack developer intern`,
        company: `iShare Incubator`,
        location: `Wynyard`,
        responsibility: [
          `Working within a team to build property management web application`,
          `Creating functional page components, coding correlative front-end and back-end`,
          `Optimization of business processes`,
        ],
        date: `May 2020 - Aug 2020`,
      },
      {
        id: 2,
        title: `Front-end developer intern`,
        company: `Netstripes`,
        location: `Pyrmont`,
        responsibility: [
          `Assisting WordPress theme development based on designs`,
          `Administrating integrations with other platforms, managing website’s plugins`,
          `Contribution of digital transformation solutions`,
          `General IT troubleshooting`,
        ],
        date: `Oct 2018 - Jan 2019`,
      },
    ],
  },
  pathPrefix: `/portfolio/public`,
};
